version: '3'
services:
  node:
    restart: always
    build: .
    image: bigbelka/librarian_node
    volumes:
      - ./:/code
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:
